// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sdvenbtlvyrmkejtbrnj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNkdmVuYnRsdnlybWtlanRicm5qIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzY3NzY2MjQsImV4cCI6MjA1MjM1MjYyNH0.dD1xmEmVcUyD1D9qEjVJyIQHMcsh3rnG6MIjsNWfCn8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);